! AUTO-GENERATED by gen_fortran_wrapper.py — do not edit manually.
! Provides velocity_tendencies_gpu as a drop-in replacement for
! velocity_tendencies, calling the DaCe GPU shared library.
MODULE vt_wrapper
  USE, INTRINSIC :: iso_c_binding
  USE f90_glue_vt_serde, ONLY: &
    glue_global_data_type, glue_t_patch, glue_t_int_state, &
    glue_t_nh_prog, glue_t_nh_metrics, glue_t_nh_diag, &
    ctor
  USE mo_model_domain, ONLY: t_patch
  USE mo_intp_data_strc, ONLY: t_int_state
  USE mo_nonhydro_types, ONLY: t_nh_prog, t_nh_metrics, t_nh_diag
  USE mo_kind, ONLY: wp, vp
  USE mo_parallel_config, ONLY: nproma
  USE mo_init_vgrid, ONLY: nflatlev
  USE mo_mpi, ONLY: i_am_accel_node
  USE mo_nonhydrostatic_config, ONLY: lextra_diffu
  USE mo_run_config, ONLY: timers_level
  USE mo_timer, ONLY: timer_intp, timer_solve_nh_veltend, timer_start, timer_stop
  USE mo_vertical_grid, ONLY: nrdmax
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: velocity_tendencies_gpu, velocity_gpu_init, velocity_gpu_finalize

  TYPE(c_ptr) :: state_lvn_only_0_istep_1 = c_null_ptr
  TYPE(c_ptr) :: state_lvn_only_0_istep_2 = c_null_ptr
  TYPE(c_ptr) :: state_lvn_only_1_istep_1 = c_null_ptr
  TYPE(c_ptr) :: state_lvn_only_1_istep_2 = c_null_ptr

  INTERFACE

    FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_1( &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        __f2dace_OA_z_w_concorr_me_d_0_s, &
        __f2dace_OA_z_w_concorr_me_d_1_s, &
        __f2dace_OA_z_w_concorr_me_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) RESULT(state_ptr) BIND(C, NAME='__dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
      TYPE(c_ptr) :: state_ptr
    END FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_1

    SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_0_istep_1( &
        state_ptr, &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        __f2dace_OA_z_w_concorr_me_d_0_s, &
        __f2dace_OA_z_w_concorr_me_d_1_s, &
        __f2dace_OA_z_w_concorr_me_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) BIND(C, NAME='__program_velocity_no_nproma_if_prop_lvn_only_0_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
    END SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_0_istep_1

    FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_1(state_ptr) RESULT(rc) BIND(C, NAME='__dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      INTEGER(c_int) :: rc
    END FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_1


    FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_2( &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) RESULT(state_ptr) BIND(C, NAME='__dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
      TYPE(c_ptr) :: state_ptr
    END FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_2

    SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_0_istep_2( &
        state_ptr, &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) BIND(C, NAME='__program_velocity_no_nproma_if_prop_lvn_only_0_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
    END SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_0_istep_2

    FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_2(state_ptr) RESULT(rc) BIND(C, NAME='__dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      INTEGER(c_int) :: rc
    END FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_2


    FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_1( &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        __f2dace_OA_z_w_concorr_me_d_0_s, &
        __f2dace_OA_z_w_concorr_me_d_1_s, &
        __f2dace_OA_z_w_concorr_me_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) RESULT(state_ptr) BIND(C, NAME='__dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
      TYPE(c_ptr) :: state_ptr
    END FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_1

    SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_1_istep_1( &
        state_ptr, &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        __f2dace_OA_z_vt_ie_d_0_s, &
        __f2dace_OA_z_vt_ie_d_1_s, &
        __f2dace_OA_z_vt_ie_d_2_s, &
        __f2dace_OA_z_w_concorr_me_d_0_s, &
        __f2dace_OA_z_w_concorr_me_d_1_s, &
        __f2dace_OA_z_w_concorr_me_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) BIND(C, NAME='__program_velocity_no_nproma_if_prop_lvn_only_1_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_w_concorr_me_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
    END SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_1_istep_1

    FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_1(state_ptr) RESULT(rc) BIND(C, NAME='__dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_1')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      INTEGER(c_int) :: rc
    END FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_1


    FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_2( &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) RESULT(state_ptr) BIND(C, NAME='__dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
      TYPE(c_ptr) :: state_ptr
    END FUNCTION __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_2

    SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_1_istep_2( &
        state_ptr, &
        global_data, &
        p_diag, &
        p_int, &
        p_metrics, &
        p_patch, &
        p_prog, &
        z_kin_hor_e, &
        z_vt_ie, &
        z_w_concorr_me, &
        __f2dace_A_z_kin_hor_e_d_0_s, &
        __f2dace_A_z_kin_hor_e_d_1_s, &
        __f2dace_A_z_kin_hor_e_d_2_s, &
        __f2dace_A_z_vt_ie_d_0_s, &
        __f2dace_A_z_vt_ie_d_1_s, &
        __f2dace_A_z_vt_ie_d_2_s, &
        __f2dace_A_z_w_concorr_me_d_0_s, &
        __f2dace_A_z_w_concorr_me_d_1_s, &
        __f2dace_A_z_w_concorr_me_d_2_s, &
        __f2dace_OA_z_kin_hor_e_d_0_s, &
        __f2dace_OA_z_kin_hor_e_d_1_s, &
        __f2dace_OA_z_kin_hor_e_d_2_s, &
        dt_linintp_ubc, &
        dtime, &
        istep, &
        ldeepatmo, &
        lvn_only, &
        ntnd &
    ) BIND(C, NAME='__program_velocity_no_nproma_if_prop_lvn_only_1_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      TYPE(c_ptr), VALUE :: global_data
      TYPE(c_ptr), VALUE :: p_diag
      TYPE(c_ptr), VALUE :: p_int
      TYPE(c_ptr), VALUE :: p_metrics
      TYPE(c_ptr), VALUE :: p_patch
      TYPE(c_ptr), VALUE :: p_prog
      TYPE(c_ptr), VALUE :: z_kin_hor_e
      TYPE(c_ptr), VALUE :: z_vt_ie
      TYPE(c_ptr), VALUE :: z_w_concorr_me
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_kin_hor_e_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_vt_ie_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_A_z_w_concorr_me_d_2_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_0_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_1_s
      INTEGER(c_int), VALUE :: __f2dace_OA_z_kin_hor_e_d_2_s
      REAL(c_double), VALUE :: dt_linintp_ubc
      REAL(c_double), VALUE :: dtime
      INTEGER(c_int), VALUE :: istep
      INTEGER(c_int), VALUE :: ldeepatmo
      INTEGER(c_int), VALUE :: lvn_only
      INTEGER(c_int), VALUE :: ntnd
    END SUBROUTINE __program_velocity_no_nproma_if_prop_lvn_only_1_istep_2

    FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_2(state_ptr) RESULT(rc) BIND(C, NAME='__dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_2')
      USE, INTRINSIC :: iso_c_binding
      IMPLICIT NONE
      TYPE(c_ptr), VALUE :: state_ptr
      INTEGER(c_int) :: rc
    END FUNCTION __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_2

  END INTERFACE

CONTAINS

  SUBROUTINE velocity_gpu_init()
    ! Placeholder — actual init happens lazily on first call per variant.
  END SUBROUTINE velocity_gpu_init

  SUBROUTINE velocity_gpu_finalize()
    INTEGER(c_int) :: rc
    IF (C_ASSOCIATED(state_lvn_only_0_istep_1)) THEN
      rc = __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_1(state_lvn_only_0_istep_1)
      state_lvn_only_0_istep_1 = c_null_ptr
    END IF
    IF (C_ASSOCIATED(state_lvn_only_0_istep_2)) THEN
      rc = __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_2(state_lvn_only_0_istep_2)
      state_lvn_only_0_istep_2 = c_null_ptr
    END IF
    IF (C_ASSOCIATED(state_lvn_only_1_istep_1)) THEN
      rc = __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_1(state_lvn_only_1_istep_1)
      state_lvn_only_1_istep_1 = c_null_ptr
    END IF
    IF (C_ASSOCIATED(state_lvn_only_1_istep_2)) THEN
      rc = __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_2(state_lvn_only_1_istep_2)
      state_lvn_only_1_istep_2 = c_null_ptr
    END IF
  END SUBROUTINE velocity_gpu_finalize

  SUBROUTINE init_global_data(g)
    TYPE(glue_global_data_type), INTENT(OUT) :: g
    INTEGER(c_int), ALLOCATABLE, TARGET, SAVE :: a_nflatlev(:), a_nrdmax(:)
    IF (.NOT. ALLOCATED(a_nflatlev)) THEN
      ALLOCATE(a_nflatlev(1))
      a_nflatlev = INT(nflatlev, c_int)
    END IF
    IF (.NOT. ALLOCATED(a_nrdmax)) THEN
      ALLOCATE(a_nrdmax(1))
      a_nrdmax = INT(nrdmax, c_int)
    END IF
    ! Fields used by velocity_tendencies (rest is zero from INTENT(OUT))
    g%m_nflatlev = c_loc(a_nflatlev)
    g%m_nrdmax = c_loc(a_nrdmax)
    g%m_nproma = INT(nproma, c_int)
    g%m_i_am_accel_node = MERGE(1_c_int, 0_c_int, i_am_accel_node)
    g%m_lextra_diffu = MERGE(1_c_int, 0_c_int, lextra_diffu)
    g%m_timers_level = INT(timers_level, c_int)
    g%m_timer_intp = INT(timer_intp, c_int)
    g%m_timer_solve_nh_veltend = INT(timer_solve_nh_veltend, c_int)
  END SUBROUTINE init_global_data

  SUBROUTINE velocity_tendencies_gpu(p_prog, p_patch, p_int, p_metrics, p_diag, &
      z_w_concorr_me, z_kin_hor_e, z_vt_ie, ntnd, istep, lvn_only, &
      dtime, dt_linintp_ubc, ldeepatmo)
    TYPE(t_nh_prog), INTENT(INOUT), TARGET :: p_prog
    TYPE(t_patch), INTENT(IN), TARGET :: p_patch
    TYPE(t_int_state), INTENT(IN), TARGET :: p_int
    TYPE(t_nh_metrics), INTENT(INOUT), TARGET :: p_metrics
    TYPE(t_nh_diag), INTENT(INOUT), TARGET :: p_diag
    REAL(vp), DIMENSION(:,:,:), INTENT(INOUT), TARGET :: z_w_concorr_me, z_kin_hor_e, z_vt_ie
    INTEGER, INTENT(IN) :: ntnd, istep
    LOGICAL, INTENT(IN) :: lvn_only, ldeepatmo
    REAL(wp), INTENT(IN) :: dtime, dt_linintp_ubc

    ! Glue structs (C-compatible deep copies)
    TYPE(glue_t_patch), TARGET :: g_patch
    TYPE(glue_t_int_state), TARGET :: g_int
    TYPE(glue_t_nh_prog), TARGET :: g_prog
    TYPE(glue_t_nh_metrics), TARGET :: g_metrics
    TYPE(glue_t_nh_diag), TARGET :: g_diag
    TYPE(glue_global_data_type), TARGET :: g_global

    ! Scalar conversions
    INTEGER(c_int) :: c_istep, c_ntnd, c_lvn_only, c_ldeepatmo
    REAL(c_double) :: c_dtime, c_dt_linintp_ubc

    ! For copy-back of p_diag output arrays
    REAL(c_double), POINTER :: ptr_ddt_vn(:,:,:,:)
    REAL(c_double), POINTER :: ptr_ddt_w(:,:,:,:)
    REAL(c_double), POINTER :: ptr_vn_ie(:,:,:)
    REAL(c_double), POINTER :: ptr_vt(:,:,:)
    REAL(c_double), POINTER :: ptr_w_concorr_c(:,:,:)

    CALL timer_start(timer_solve_nh_veltend)

    ! Pack Fortran structs into C-compatible glue types
    CALL ctor(p_patch, g_patch, .TRUE.)
    CALL ctor(p_int, g_int, .TRUE.)
    CALL ctor(p_prog, g_prog, .TRUE.)
    CALL ctor(p_metrics, g_metrics, .TRUE.)
    CALL ctor(p_diag, g_diag, .TRUE.)
    CALL init_global_data(g_global)

    ! Convert scalars
    c_istep = INT(istep, c_int)
    c_ntnd = INT(ntnd, c_int)
    c_lvn_only = MERGE(1_c_int, 0_c_int, lvn_only)
    c_ldeepatmo = MERGE(1_c_int, 0_c_int, ldeepatmo)
    c_dtime = REAL(dtime, c_double)
    c_dt_linintp_ubc = REAL(dt_linintp_ubc, c_double)

    IF (lvn_only .EQV. .FALSE. .AND. istep == 1) THEN
      IF (.NOT. C_ASSOCIATED(state_lvn_only_0_istep_1)) THEN
        state_lvn_only_0_istep_1 = __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_1( &
          c_loc(g_global), &
          c_loc(g_diag), &
          c_loc(g_int), &
          c_loc(g_metrics), &
          c_loc(g_patch), &
          c_loc(g_prog), &
          c_loc(z_kin_hor_e(1,1,1)), &
          c_loc(z_vt_ie(1,1,1)), &
          c_loc(z_w_concorr_me(1,1,1)), &
          INT(SIZE(z_kin_hor_e, 1), c_int), &
          INT(SIZE(z_kin_hor_e, 2), c_int), &
          INT(SIZE(z_kin_hor_e, 3), c_int), &
          INT(SIZE(z_vt_ie, 1), c_int), &
          INT(SIZE(z_vt_ie, 2), c_int), &
          INT(SIZE(z_vt_ie, 3), c_int), &
          INT(SIZE(z_w_concorr_me, 1), c_int), &
          INT(SIZE(z_w_concorr_me, 2), c_int), &
          INT(SIZE(z_w_concorr_me, 3), c_int), &
          INT(LBOUND(z_kin_hor_e, 1), c_int), &
          INT(LBOUND(z_kin_hor_e, 2), c_int), &
          INT(LBOUND(z_kin_hor_e, 3), c_int), &
          INT(LBOUND(z_vt_ie, 1), c_int), &
          INT(LBOUND(z_vt_ie, 2), c_int), &
          INT(LBOUND(z_vt_ie, 3), c_int), &
          INT(LBOUND(z_w_concorr_me, 1), c_int), &
          INT(LBOUND(z_w_concorr_me, 2), c_int), &
          INT(LBOUND(z_w_concorr_me, 3), c_int), &
          c_dt_linintp_ubc, &
          c_dtime, &
          c_istep, &
          c_ldeepatmo, &
          c_lvn_only, &
          c_ntnd &
        )
      END IF
      CALL __program_velocity_no_nproma_if_prop_lvn_only_0_istep_1( &
        state_lvn_only_0_istep_1, &
        c_loc(g_global), &
        c_loc(g_diag), &
        c_loc(g_int), &
        c_loc(g_metrics), &
        c_loc(g_patch), &
        c_loc(g_prog), &
        c_loc(z_kin_hor_e(1,1,1)), &
        c_loc(z_vt_ie(1,1,1)), &
        c_loc(z_w_concorr_me(1,1,1)), &
        INT(SIZE(z_kin_hor_e, 1), c_int), &
        INT(SIZE(z_kin_hor_e, 2), c_int), &
        INT(SIZE(z_kin_hor_e, 3), c_int), &
        INT(SIZE(z_vt_ie, 1), c_int), &
        INT(SIZE(z_vt_ie, 2), c_int), &
        INT(SIZE(z_vt_ie, 3), c_int), &
        INT(SIZE(z_w_concorr_me, 1), c_int), &
        INT(SIZE(z_w_concorr_me, 2), c_int), &
        INT(SIZE(z_w_concorr_me, 3), c_int), &
        INT(LBOUND(z_kin_hor_e, 1), c_int), &
        INT(LBOUND(z_kin_hor_e, 2), c_int), &
        INT(LBOUND(z_kin_hor_e, 3), c_int), &
        INT(LBOUND(z_vt_ie, 1), c_int), &
        INT(LBOUND(z_vt_ie, 2), c_int), &
        INT(LBOUND(z_vt_ie, 3), c_int), &
        INT(LBOUND(z_w_concorr_me, 1), c_int), &
        INT(LBOUND(z_w_concorr_me, 2), c_int), &
        INT(LBOUND(z_w_concorr_me, 3), c_int), &
        c_dt_linintp_ubc, &
        c_dtime, &
        c_istep, &
        c_ldeepatmo, &
        c_lvn_only, &
        c_ntnd &
      )

    ELSE IF (lvn_only .EQV. .FALSE. .AND. istep == 2) THEN
      IF (.NOT. C_ASSOCIATED(state_lvn_only_0_istep_2)) THEN
        state_lvn_only_0_istep_2 = __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_2( &
          c_loc(g_global), &
          c_loc(g_diag), &
          c_loc(g_int), &
          c_loc(g_metrics), &
          c_loc(g_patch), &
          c_loc(g_prog), &
          c_loc(z_kin_hor_e(1,1,1)), &
          c_loc(z_vt_ie(1,1,1)), &
          c_loc(z_w_concorr_me(1,1,1)), &
          INT(SIZE(z_kin_hor_e, 1), c_int), &
          INT(SIZE(z_kin_hor_e, 2), c_int), &
          INT(SIZE(z_kin_hor_e, 3), c_int), &
          INT(SIZE(z_vt_ie, 1), c_int), &
          INT(SIZE(z_vt_ie, 2), c_int), &
          INT(SIZE(z_vt_ie, 3), c_int), &
          INT(SIZE(z_w_concorr_me, 1), c_int), &
          INT(SIZE(z_w_concorr_me, 2), c_int), &
          INT(SIZE(z_w_concorr_me, 3), c_int), &
          INT(LBOUND(z_kin_hor_e, 1), c_int), &
          INT(LBOUND(z_kin_hor_e, 2), c_int), &
          INT(LBOUND(z_kin_hor_e, 3), c_int), &
          INT(LBOUND(z_vt_ie, 1), c_int), &
          INT(LBOUND(z_vt_ie, 2), c_int), &
          INT(LBOUND(z_vt_ie, 3), c_int), &
          c_dt_linintp_ubc, &
          c_dtime, &
          c_istep, &
          c_ldeepatmo, &
          c_lvn_only, &
          c_ntnd &
        )
      END IF
      CALL __program_velocity_no_nproma_if_prop_lvn_only_0_istep_2( &
        state_lvn_only_0_istep_2, &
        c_loc(g_global), &
        c_loc(g_diag), &
        c_loc(g_int), &
        c_loc(g_metrics), &
        c_loc(g_patch), &
        c_loc(g_prog), &
        c_loc(z_kin_hor_e(1,1,1)), &
        c_loc(z_vt_ie(1,1,1)), &
        c_loc(z_w_concorr_me(1,1,1)), &
        INT(SIZE(z_kin_hor_e, 1), c_int), &
        INT(SIZE(z_kin_hor_e, 2), c_int), &
        INT(SIZE(z_kin_hor_e, 3), c_int), &
        INT(SIZE(z_vt_ie, 1), c_int), &
        INT(SIZE(z_vt_ie, 2), c_int), &
        INT(SIZE(z_vt_ie, 3), c_int), &
        INT(SIZE(z_w_concorr_me, 1), c_int), &
        INT(SIZE(z_w_concorr_me, 2), c_int), &
        INT(SIZE(z_w_concorr_me, 3), c_int), &
        INT(LBOUND(z_kin_hor_e, 1), c_int), &
        INT(LBOUND(z_kin_hor_e, 2), c_int), &
        INT(LBOUND(z_kin_hor_e, 3), c_int), &
        INT(LBOUND(z_vt_ie, 1), c_int), &
        INT(LBOUND(z_vt_ie, 2), c_int), &
        INT(LBOUND(z_vt_ie, 3), c_int), &
        c_dt_linintp_ubc, &
        c_dtime, &
        c_istep, &
        c_ldeepatmo, &
        c_lvn_only, &
        c_ntnd &
      )

    ELSE IF (lvn_only .EQV. .TRUE. .AND. istep == 1) THEN
      IF (.NOT. C_ASSOCIATED(state_lvn_only_1_istep_1)) THEN
        state_lvn_only_1_istep_1 = __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_1( &
          c_loc(g_global), &
          c_loc(g_diag), &
          c_loc(g_int), &
          c_loc(g_metrics), &
          c_loc(g_patch), &
          c_loc(g_prog), &
          c_loc(z_kin_hor_e(1,1,1)), &
          c_loc(z_vt_ie(1,1,1)), &
          c_loc(z_w_concorr_me(1,1,1)), &
          INT(SIZE(z_kin_hor_e, 1), c_int), &
          INT(SIZE(z_kin_hor_e, 2), c_int), &
          INT(SIZE(z_kin_hor_e, 3), c_int), &
          INT(SIZE(z_vt_ie, 1), c_int), &
          INT(SIZE(z_vt_ie, 2), c_int), &
          INT(SIZE(z_vt_ie, 3), c_int), &
          INT(SIZE(z_w_concorr_me, 1), c_int), &
          INT(SIZE(z_w_concorr_me, 2), c_int), &
          INT(SIZE(z_w_concorr_me, 3), c_int), &
          INT(LBOUND(z_kin_hor_e, 1), c_int), &
          INT(LBOUND(z_kin_hor_e, 2), c_int), &
          INT(LBOUND(z_kin_hor_e, 3), c_int), &
          INT(LBOUND(z_vt_ie, 1), c_int), &
          INT(LBOUND(z_vt_ie, 2), c_int), &
          INT(LBOUND(z_vt_ie, 3), c_int), &
          INT(LBOUND(z_w_concorr_me, 1), c_int), &
          INT(LBOUND(z_w_concorr_me, 2), c_int), &
          INT(LBOUND(z_w_concorr_me, 3), c_int), &
          c_dt_linintp_ubc, &
          c_dtime, &
          c_istep, &
          c_ldeepatmo, &
          c_lvn_only, &
          c_ntnd &
        )
      END IF
      CALL __program_velocity_no_nproma_if_prop_lvn_only_1_istep_1( &
        state_lvn_only_1_istep_1, &
        c_loc(g_global), &
        c_loc(g_diag), &
        c_loc(g_int), &
        c_loc(g_metrics), &
        c_loc(g_patch), &
        c_loc(g_prog), &
        c_loc(z_kin_hor_e(1,1,1)), &
        c_loc(z_vt_ie(1,1,1)), &
        c_loc(z_w_concorr_me(1,1,1)), &
        INT(SIZE(z_kin_hor_e, 1), c_int), &
        INT(SIZE(z_kin_hor_e, 2), c_int), &
        INT(SIZE(z_kin_hor_e, 3), c_int), &
        INT(SIZE(z_vt_ie, 1), c_int), &
        INT(SIZE(z_vt_ie, 2), c_int), &
        INT(SIZE(z_vt_ie, 3), c_int), &
        INT(SIZE(z_w_concorr_me, 1), c_int), &
        INT(SIZE(z_w_concorr_me, 2), c_int), &
        INT(SIZE(z_w_concorr_me, 3), c_int), &
        INT(LBOUND(z_kin_hor_e, 1), c_int), &
        INT(LBOUND(z_kin_hor_e, 2), c_int), &
        INT(LBOUND(z_kin_hor_e, 3), c_int), &
        INT(LBOUND(z_vt_ie, 1), c_int), &
        INT(LBOUND(z_vt_ie, 2), c_int), &
        INT(LBOUND(z_vt_ie, 3), c_int), &
        INT(LBOUND(z_w_concorr_me, 1), c_int), &
        INT(LBOUND(z_w_concorr_me, 2), c_int), &
        INT(LBOUND(z_w_concorr_me, 3), c_int), &
        c_dt_linintp_ubc, &
        c_dtime, &
        c_istep, &
        c_ldeepatmo, &
        c_lvn_only, &
        c_ntnd &
      )

    ELSE IF (lvn_only .EQV. .TRUE. .AND. istep == 2) THEN
      IF (.NOT. C_ASSOCIATED(state_lvn_only_1_istep_2)) THEN
        state_lvn_only_1_istep_2 = __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_2( &
          c_loc(g_global), &
          c_loc(g_diag), &
          c_loc(g_int), &
          c_loc(g_metrics), &
          c_loc(g_patch), &
          c_loc(g_prog), &
          c_loc(z_kin_hor_e(1,1,1)), &
          c_loc(z_vt_ie(1,1,1)), &
          c_loc(z_w_concorr_me(1,1,1)), &
          INT(SIZE(z_kin_hor_e, 1), c_int), &
          INT(SIZE(z_kin_hor_e, 2), c_int), &
          INT(SIZE(z_kin_hor_e, 3), c_int), &
          INT(SIZE(z_vt_ie, 1), c_int), &
          INT(SIZE(z_vt_ie, 2), c_int), &
          INT(SIZE(z_vt_ie, 3), c_int), &
          INT(SIZE(z_w_concorr_me, 1), c_int), &
          INT(SIZE(z_w_concorr_me, 2), c_int), &
          INT(SIZE(z_w_concorr_me, 3), c_int), &
          INT(LBOUND(z_kin_hor_e, 1), c_int), &
          INT(LBOUND(z_kin_hor_e, 2), c_int), &
          INT(LBOUND(z_kin_hor_e, 3), c_int), &
          c_dt_linintp_ubc, &
          c_dtime, &
          c_istep, &
          c_ldeepatmo, &
          c_lvn_only, &
          c_ntnd &
        )
      END IF
      CALL __program_velocity_no_nproma_if_prop_lvn_only_1_istep_2( &
        state_lvn_only_1_istep_2, &
        c_loc(g_global), &
        c_loc(g_diag), &
        c_loc(g_int), &
        c_loc(g_metrics), &
        c_loc(g_patch), &
        c_loc(g_prog), &
        c_loc(z_kin_hor_e(1,1,1)), &
        c_loc(z_vt_ie(1,1,1)), &
        c_loc(z_w_concorr_me(1,1,1)), &
        INT(SIZE(z_kin_hor_e, 1), c_int), &
        INT(SIZE(z_kin_hor_e, 2), c_int), &
        INT(SIZE(z_kin_hor_e, 3), c_int), &
        INT(SIZE(z_vt_ie, 1), c_int), &
        INT(SIZE(z_vt_ie, 2), c_int), &
        INT(SIZE(z_vt_ie, 3), c_int), &
        INT(SIZE(z_w_concorr_me, 1), c_int), &
        INT(SIZE(z_w_concorr_me, 2), c_int), &
        INT(SIZE(z_w_concorr_me, 3), c_int), &
        INT(LBOUND(z_kin_hor_e, 1), c_int), &
        INT(LBOUND(z_kin_hor_e, 2), c_int), &
        INT(LBOUND(z_kin_hor_e, 3), c_int), &
        c_dt_linintp_ubc, &
        c_dtime, &
        c_istep, &
        c_ldeepatmo, &
        c_lvn_only, &
        c_ntnd &
      )

    END IF

    ! ---- Copy results back from glue structs to Fortran types ----
    ! The DaCe library wrote into the deep-copied arrays inside g_diag.
    ! We need to copy them back into the original Fortran p_diag fields.

    ! max_vcfl_dyn (scalar field in glue struct, modified by DaCe)
    p_diag%max_vcfl_dyn = g_diag%m_max_vcfl_dyn

    CALL c_f_pointer(g_diag%m_ddt_vn_apc_pc, ptr_ddt_vn, [g_diag%m___f2dace_SA_ddt_vn_apc_pc_d_0_s_300, g_diag%m___f2dace_SA_ddt_vn_apc_pc_d_1_s_301, g_diag%m___f2dace_SA_ddt_vn_apc_pc_d_2_s_302, g_diag%m___f2dace_SA_ddt_vn_apc_pc_d_3_s_303])
    p_diag%ddt_vn_apc_pc = ptr_ddt_vn

    CALL c_f_pointer(g_diag%m_ddt_w_adv_pc, ptr_ddt_w, [g_diag%m___f2dace_SA_ddt_w_adv_pc_d_0_s_304, g_diag%m___f2dace_SA_ddt_w_adv_pc_d_1_s_305, g_diag%m___f2dace_SA_ddt_w_adv_pc_d_2_s_306, g_diag%m___f2dace_SA_ddt_w_adv_pc_d_3_s_307])
    p_diag%ddt_w_adv_pc = ptr_ddt_w

    CALL c_f_pointer(g_diag%m_vn_ie, ptr_vn_ie, [g_diag%m___f2dace_SA_vn_ie_d_0_s_294, g_diag%m___f2dace_SA_vn_ie_d_1_s_295, g_diag%m___f2dace_SA_vn_ie_d_2_s_296])
    p_diag%vn_ie = ptr_vn_ie

    CALL c_f_pointer(g_diag%m_vt, ptr_vt, [g_diag%m___f2dace_SA_vt_d_0_s_291, g_diag%m___f2dace_SA_vt_d_1_s_292, g_diag%m___f2dace_SA_vt_d_2_s_293])
    p_diag%vt = ptr_vt

    CALL c_f_pointer(g_diag%m_w_concorr_c, ptr_w_concorr_c, [g_diag%m___f2dace_SA_w_concorr_c_d_0_s_297, g_diag%m___f2dace_SA_w_concorr_c_d_1_s_298, g_diag%m___f2dace_SA_w_concorr_c_d_2_s_299])
    p_diag%w_concorr_c = ptr_w_concorr_c

    CALL timer_stop(timer_solve_nh_veltend)

  END SUBROUTINE velocity_tendencies_gpu

END MODULE vt_wrapper