#run for all commits to the master branch and for merge requests
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# coverage:
#   - generates the coverage report data
# tests:
#   - run_test_*: build and test yaxt
#   - check_warning_*: checks output of run_test_* compiler outputs
#     - fails if it contains warings -> pipeline can still run
#       successfully, but with warning
# documentation:
#   - generate html doxygen documentation and html coverage report
# publish
#   - uploads html pages
stages:
  - tests
  - coverage
  - documentation
  - publish

.load_basic_modules: &load_basic_modules
  - . /sw/etc/profile.levante
  - module purge
  - module load git python3

.init_build:
  before_script:
    - *load_basic_modules
  tags:
    - levante, xen

.init_build_gcc_11_2_0:
  extends: .init_build
  before_script:
    - *load_basic_modules
    - module load gcc/11.2.0-gcc-11.2.0 openmpi/4.1.2-gcc-11.2.0

.install_gcovr: &install_gcovr
  - mkdir $CI_PROJECT_DIR/install_dir
  - python3 -m venv $CI_PROJECT_DIR/install_dir/python-venv/gcovr
  - . $CI_PROJECT_DIR/install_dir/python-venv/gcovr/bin/activate
# 'jinja2<3.1' is required to avoid bug, which was fixed in gcovr 5.1
# gcovr 5.0 is required because newer version had other issues
  - pip install 'jinja2<3.1' gcovr==5.0

.check_warning:
  variables:
    GIT_STRATEGY: none
    AWK_SCRIPT: '/warning/ || /WARNING/ || /Warning/'
  script:
    - awk "$AWK_SCRIPT" $OUTPUT_FILE > awk.out
    - "if [ -s awk.out ]; then cat awk.out; exit 1; fi"
  allow_failure: true
  tags:
  - doxygen

gen_cov_data:
  stage: coverage
  dependencies: []
  extends: .init_build_gcc_11_2_0
  script:
    - export OMPI_MCA_btl_sm_use_knem=0
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - autoreconf -i
    - >
      ./configure
      CC=mpicc FC=mpifort
      FCFLAGS="-O0 -g -cpp -fprofile-arcs -ftest-coverage"
      CFLAGS="-O0 -g -Wall -fprofile-arcs -ftest-coverage"
      MPI_LAUNCH="`which mpirun` --oversubscribe"
    - make -j8 check
  artifacts:
    paths:
      - ./*.gcno
      - ./*/*.gcno
      - ./*/*/*.gcno
      - ./*/*/*/*.gcno
      - ./*.gcda
      - ./*/*.gcda
      - ./*/*/*.gcda
      - ./*/*/*/*.gcda
    expire_in: 5min

run_test_gcc_11_2_0:
  stage: tests
  extends: .init_build_gcc_11_2_0
  script:
    - export OMPI_MCA_btl_sm_use_knem=0
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - autoreconf -i
    - >
      ./configure
      CC=mpicc FC=mpifort
      FCFLAGS="-O0 -g -cpp"
      CFLAGS="-O0 -g -Wall"
      --disable-silent-rules
      MPI_LAUNCH="`which mpirun` --oversubscribe"
# build yaxt and unit tests without running tests
    - make -j8 check TESTS= XFAIL_TESTS= 2> >(tee make.err)
# run tests
    - make check
  artifacts:
    paths:
      - make.err
    expire_in: 5min

gen_doxy_html:
  stage: documentation
  needs:
    - job: gen_cov_data
      artifacts: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  script:
  - make -C doc
  - doxygen doc/Doxyfile 2> >(tee doxy.err)
  artifacts:
    expire_in: 5min
    paths:
    - doc/html
    - doxy.err
  tags:
  - doxygen

gen_cov_rep_html:
  stage: documentation
  needs:
    - gen_cov_data
  extends: .init_build_gcc_11_2_0
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  script:
    - *install_gcovr
    - mkdir coverage
    - cd src
    - >
      gcovr
      --html-details
      --exclude-unreachable-branches
      --print-summary
      -o ../coverage/index.html
      --root ..
      --object-directory .
      -e ../examples
      -e ../tests
      -e ../include
      -e ../perf
    - cd ..
    - mkdir coverage_tests
    - cd tests
    - >
      gcovr
      --html-details
      --exclude-unreachable-branches
      -o ../coverage_tests/index.html
      --root ..
      --object-directory .
      -e ../examples
      -e ../src
      -e ../include
      -e ../perf
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    paths:
      - coverage/
      - coverage_tests/
    expire_in: 5min

check_warning_gcc_11_2_0:
  stage: tests
  extends: .check_warning
  variables:
    OUTPUT_FILE: make.err
  needs:
    - run_test_gcc_11_2_0

check_warning_doxy:
  stage: documentation
  extends: .check_warning
  variables:
    AWK_SCRIPT: '/warning/ && !/doc\/Doxyfile/ && !/doxygen -u/ && !/DOT_GRAPH_MAX_NODES/'
    OUTPUT_FILE: doxy.err
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  needs:
    - gen_doxy_html

pages:
  stage: publish
  variables:
    GIT_STRATEGY: none
  needs:
    - gen_cov_rep_html
    - gen_doxy_html
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  script:
  - mv doc/html/ public/
  - mv coverage/ public/coverage
  - mv coverage_tests public/coverage_tests
  artifacts:
    expire_in: 5min
    paths:
    - public
  tags:
  - doxygen

#generate coverage report for diff view of merge request
gen_cov_rep_xml:
  stage: documentation
  needs:
    - gen_cov_data
  extends: .init_build_gcc_11_2_0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  script:
  script:
    - *install_gcovr
    - gcovr --xml-pretty --exclude-unreachable-branches -o coverage.xml --root .
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
   expire_in: 1 week
   reports:
     coverage_report:
       coverage_format: cobertura
       path: coverage.xml
