! TODO: Must keep this in sync with https://github.com/spcl/icon-artifacts/blob/pratyai/solve_nh/solve_nh/include/shared_struct_defs.h


module mo_solve_nh_dace_structs

  use iso_c_binding

  type, bind(c) :: dace_global_data_type
    ! C++: double divdamp_fac = {}; (missing)
    real(kind=c_double) :: divdamp_fac
    ! C++: double divdamp_fac_o2 = {}; (missing)
    real(kind=c_double) :: divdamp_fac_o2
    ! C++: double iau_wgt_dyn = {};
    real(kind=c_double) :: iau_wgt_dyn
    ! C++: int divdamp_order = {}; (missing)
    integer(kind=c_int) :: divdamp_order
    ! C++: int divdamp_type = {}; (missing)
    integer(kind=c_int) :: divdamp_type
    ! C++: int grf_intmethod_e = {};
    integer(kind=c_int) :: grf_intmethod_e
    ! C++: int i_am_accel_node = {};
    integer(kind=c_int) :: i_am_accel_node
    ! C++: int iadv_rhotheta = {};
    integer(kind=c_int) :: iadv_rhotheta
    ! C++: int igradp_method = {};
    integer(kind=c_int) :: igradp_method
    ! C++: int is_iau_active = {};
    integer(kind=c_int) :: is_iau_active
    ! C++: int itime_scheme = {};
    integer(kind=c_int) :: itime_scheme
    ! C++: int l_limited_area = {};
    integer(kind=c_int) :: l_limited_area
    ! C++: int ldeepatmo = {};
    integer(kind=c_int) :: ldeepatmo
    ! C++: int lextra_diffu = {};
    integer(kind=c_int) :: lextra_diffu
    ! C++: int lvert_nest = {};
    integer(kind=c_int) :: lvert_nest
    ! C++: int nproma = {};
    integer(kind=c_int) :: nproma
    ! C++: int rayleigh_type = {};
    integer(kind=c_int) :: rayleigh_type
    ! C++: int timer_intp = {};
    integer(kind=c_int) :: timer_intp
    ! C++: int timer_solve_nh_cellcomp = {};
    integer(kind=c_int) :: timer_solve_nh_cellcomp
    ! C++: int timer_solve_nh_edgecomp = {}; (missing)
    integer(kind=c_int) :: timer_solve_nh_edgecomp
    ! C++: int timer_solve_nh_veltend = {};
    integer(kind=c_int) :: timer_solve_nh_veltend
    ! C++: int timer_solve_nh_vimpl = {}; (missing)
    integer(kind=c_int) :: timer_solve_nh_vimpl
    ! C++: int timer_solve_nh_vnupd = {};
    integer(kind=c_int) :: timer_solve_nh_vnupd
    ! C++: int timers_level = {};
    integer(kind=c_int) :: timers_level
    ! C++: int *kstart_dd3d = {};
    type(c_ptr) :: kstart_dd3d
    ! C++: int *kstart_moist = {}; (missing)
    type(c_ptr) :: kstart_moist
    ! C++: int *ndyn_substeps_var = {}; (missing)
    type(c_ptr) :: ndyn_substeps_var
    ! C++: int *nflat_gradp = {};
    type(c_ptr) :: nflat_gradp
    ! C++: int *nflatlev = {};
    type(c_ptr) :: nflatlev
    ! C++: int *nrdmax = {};
    type(c_ptr) :: nrdmax
  end type dace_global_data_type

  type, bind(c) :: dace_t_tangent_vectors
    real(kind=c_double) :: v1
    real(kind=c_double) :: v2
  end type dace_t_tangent_vectors

  type, bind(c) :: dace_t_grid_edges
    integer(kind=c_int) :: f2dace_SA_area_edge_d_0_s
    integer(kind=c_int) :: f2dace_SA_area_edge_d_1_s
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_dual_normal_cell_d_0_s
    integer(kind=c_int) :: f2dace_SA_dual_normal_cell_d_1_s
    integer(kind=c_int) :: f2dace_SA_dual_normal_cell_d_2_s
    integer(kind=c_int) :: f2dace_SA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SA_f_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_f_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_fn_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_fn_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_ft_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_ft_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_inv_dual_edge_length_d_0_s
    integer(kind=c_int) :: f2dace_SA_inv_dual_edge_length_d_1_s
    integer(kind=c_int) :: f2dace_SA_inv_primal_edge_length_d_0_s
    integer(kind=c_int) :: f2dace_SA_inv_primal_edge_length_d_1_s
    integer(kind=c_int) :: f2dace_SA_primal_normal_cell_d_0_s
    integer(kind=c_int) :: f2dace_SA_primal_normal_cell_d_1_s
    integer(kind=c_int) :: f2dace_SA_primal_normal_cell_d_2_s
    integer(kind=c_int) :: f2dace_SA_quad_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_quad_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_quad_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_quad_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_quad_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_quad_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_refin_ctrl_d_0_s
    integer(kind=c_int) :: f2dace_SA_refin_ctrl_d_1_s
    integer(kind=c_int) :: f2dace_SA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_start_index_d_0_s
    integer(kind=c_int) :: f2dace_SA_tangent_orientation_d_0_s
    integer(kind=c_int) :: f2dace_SA_tangent_orientation_d_1_s
    integer(kind=c_int) :: f2dace_SA_vertex_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_vertex_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_vertex_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_vertex_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_vertex_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_vertex_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_area_edge_d_0_s
    integer(kind=c_int) :: f2dace_SOA_area_edge_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_dual_normal_cell_d_0_s
    integer(kind=c_int) :: f2dace_SOA_dual_normal_cell_d_1_s
    integer(kind=c_int) :: f2dace_SOA_dual_normal_cell_d_2_s
    integer(kind=c_int) :: f2dace_SOA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_f_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_f_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_fn_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_fn_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ft_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ft_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_inv_dual_edge_length_d_0_s
    integer(kind=c_int) :: f2dace_SOA_inv_dual_edge_length_d_1_s
    integer(kind=c_int) :: f2dace_SOA_inv_primal_edge_length_d_0_s
    integer(kind=c_int) :: f2dace_SOA_inv_primal_edge_length_d_1_s
    integer(kind=c_int) :: f2dace_SOA_primal_normal_cell_d_0_s
    integer(kind=c_int) :: f2dace_SOA_primal_normal_cell_d_1_s
    integer(kind=c_int) :: f2dace_SOA_primal_normal_cell_d_2_s
    integer(kind=c_int) :: f2dace_SOA_quad_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_quad_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_quad_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_quad_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_quad_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_quad_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_refin_ctrl_d_0_s
    integer(kind=c_int) :: f2dace_SOA_refin_ctrl_d_1_s
    integer(kind=c_int) :: f2dace_SOA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_start_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_tangent_orientation_d_0_s
    integer(kind=c_int) :: f2dace_SOA_tangent_orientation_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vertex_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vertex_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vertex_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vertex_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vertex_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vertex_idx_d_2_s
    type(c_ptr) :: area_edge
    type(c_ptr) :: cell_blk
    type(c_ptr) :: cell_idx
    type(c_ptr) :: dual_normal_cell
    type(c_ptr) :: end_block
    type(c_ptr) :: end_index
    type(c_ptr) :: f_e
    type(c_ptr) :: fn_e
    type(c_ptr) :: ft_e
    type(c_ptr) :: inv_dual_edge_length
    type(c_ptr) :: inv_primal_edge_length
    type(c_ptr) :: primal_normal_cell
    type(c_ptr) :: quad_blk
    type(c_ptr) :: quad_idx
    type(c_ptr) :: refin_ctrl
    type(c_ptr) :: start_block
    type(c_ptr) :: start_index
    type(c_ptr) :: tangent_orientation
    type(c_ptr) :: vertex_blk
    type(c_ptr) :: vertex_idx
  end type dace_t_grid_edges

  type, bind(c) :: dace_t_nh_metrics
    integer(kind=c_int) :: f2dace_SA_bdy_mflx_e_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_bdy_mflx_e_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_coeff1_dwdz_d_0_s
    integer(kind=c_int) :: f2dace_SA_coeff1_dwdz_d_1_s
    integer(kind=c_int) :: f2dace_SA_coeff1_dwdz_d_2_s
    integer(kind=c_int) :: f2dace_SA_coeff2_dwdz_d_0_s
    integer(kind=c_int) :: f2dace_SA_coeff2_dwdz_d_1_s
    integer(kind=c_int) :: f2dace_SA_coeff2_dwdz_d_2_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradekin_d_0_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradekin_d_1_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradekin_d_2_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SA_coeff_gradp_d_3_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac1_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac1_mc_d_1_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac1_mc_d_2_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac2_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac2_mc_d_1_s
    integer(kind=c_int) :: f2dace_SA_d2dexdz2_fac2_mc_d_2_s
    integer(kind=c_int) :: f2dace_SA_d_exner_dz_ref_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_d_exner_dz_ref_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_d_exner_dz_ref_ic_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_full_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_full_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_full_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_half_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_half_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddqz_z_half_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddxn_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddxn_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddxn_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddxt_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddxt_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddxt_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_divh_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_divzl_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_divzu_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_gradh_ifc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_gradh_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_invr_ifc_d_0_s
    integer(kind=c_int) :: f2dace_SA_deepatmo_invr_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_exfac_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_exfac_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_exfac_d_2_s
    integer(kind=c_int) :: f2dace_SA_exner_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SA_hmask_dd3d_d_0_s
    integer(kind=c_int) :: f2dace_SA_hmask_dd3d_d_1_s
    integer(kind=c_int) :: f2dace_SA_inv_ddqz_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SA_inv_ddqz_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SA_inv_ddqz_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SA_pg_edgeblk_d_0_s
    integer(kind=c_int) :: f2dace_SA_pg_edgeidx_d_0_s
    integer(kind=c_int) :: f2dace_SA_pg_exdist_d_0_s
    integer(kind=c_int) :: f2dace_SA_pg_vertidx_d_0_s
    integer(kind=c_int) :: f2dace_SA_rayleigh_vn_d_0_s
    integer(kind=c_int) :: f2dace_SA_rayleigh_w_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_me_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_me_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_ref_me_d_2_s
    integer(kind=c_int) :: f2dace_SA_scalfac_dd3d_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_ic_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_me_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_me_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_ref_me_d_2_s
    integer(kind=c_int) :: f2dace_SA_vertidx_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SA_vertidx_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SA_vertidx_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SA_vertidx_gradp_d_3_s
    integer(kind=c_int) :: f2dace_SA_vwind_expl_wgt_d_0_s
    integer(kind=c_int) :: f2dace_SA_vwind_expl_wgt_d_1_s
    integer(kind=c_int) :: f2dace_SA_vwind_impl_wgt_d_0_s
    integer(kind=c_int) :: f2dace_SA_vwind_impl_wgt_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_c_d_0_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_c_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_c_d_2_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfac_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq1_c_d_0_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq1_c_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq1_c_d_2_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_c_d_0_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_c_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_c_d_2_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_wgtfacq_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_zdiff_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SA_zdiff_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SA_zdiff_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SA_zdiff_gradp_d_3_s
    integer(kind=c_int) :: f2dace_SOA_bdy_mflx_e_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_bdy_mflx_e_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_coeff1_dwdz_d_0_s
    integer(kind=c_int) :: f2dace_SOA_coeff1_dwdz_d_1_s
    integer(kind=c_int) :: f2dace_SOA_coeff1_dwdz_d_2_s
    integer(kind=c_int) :: f2dace_SOA_coeff2_dwdz_d_0_s
    integer(kind=c_int) :: f2dace_SOA_coeff2_dwdz_d_1_s
    integer(kind=c_int) :: f2dace_SOA_coeff2_dwdz_d_2_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradekin_d_0_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradekin_d_1_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradekin_d_2_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SOA_coeff_gradp_d_3_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac1_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac1_mc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac1_mc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac2_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac2_mc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_d2dexdz2_fac2_mc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_d_exner_dz_ref_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_d_exner_dz_ref_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_d_exner_dz_ref_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_full_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_full_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_full_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_half_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_half_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddqz_z_half_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddxn_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddxn_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddxn_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddxt_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddxt_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddxt_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_divh_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_divzl_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_divzu_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_gradh_ifc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_gradh_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_invr_ifc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_deepatmo_invr_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_exfac_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_exfac_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_exfac_d_2_s
    integer(kind=c_int) :: f2dace_SOA_exner_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_hmask_dd3d_d_0_s
    integer(kind=c_int) :: f2dace_SOA_hmask_dd3d_d_1_s
    integer(kind=c_int) :: f2dace_SOA_inv_ddqz_z_full_d_0_s
    integer(kind=c_int) :: f2dace_SOA_inv_ddqz_z_full_d_1_s
    integer(kind=c_int) :: f2dace_SOA_inv_ddqz_z_full_d_2_s
    integer(kind=c_int) :: f2dace_SOA_pg_edgeblk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_pg_edgeidx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_pg_exdist_d_0_s
    integer(kind=c_int) :: f2dace_SOA_pg_vertidx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rayleigh_vn_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rayleigh_w_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_me_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_me_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_ref_me_d_2_s
    integer(kind=c_int) :: f2dace_SOA_scalfac_dd3d_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_mc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_mc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_mc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_me_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_me_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_ref_me_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vertidx_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vertidx_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vertidx_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vertidx_gradp_d_3_s
    integer(kind=c_int) :: f2dace_SOA_vwind_expl_wgt_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vwind_expl_wgt_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vwind_impl_wgt_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vwind_impl_wgt_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_c_d_0_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_c_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_c_d_2_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfac_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq1_c_d_0_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq1_c_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq1_c_d_2_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_c_d_0_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_c_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_c_d_2_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_wgtfacq_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_zdiff_gradp_d_0_s
    integer(kind=c_int) :: f2dace_SOA_zdiff_gradp_d_1_s
    integer(kind=c_int) :: f2dace_SOA_zdiff_gradp_d_2_s
    integer(kind=c_int) :: f2dace_SOA_zdiff_gradp_d_3_s
    type(c_ptr) :: bdy_mflx_e_blk
    integer(kind=c_int) :: bdy_mflx_e_dim
    type(c_ptr) :: bdy_mflx_e_idx
    type(c_ptr) :: coeff1_dwdz
    type(c_ptr) :: coeff2_dwdz
    type(c_ptr) :: coeff_gradekin
    type(c_ptr) :: coeff_gradp
    type(c_ptr) :: d2dexdz2_fac1_mc
    type(c_ptr) :: d2dexdz2_fac2_mc
    type(c_ptr) :: d_exner_dz_ref_ic
    type(c_ptr) :: ddqz_z_full_e
    type(c_ptr) :: ddqz_z_half
    type(c_ptr) :: ddxn_z_full
    type(c_ptr) :: ddxt_z_full
    type(c_ptr) :: deepatmo_divh_mc
    type(c_ptr) :: deepatmo_divzl_mc
    type(c_ptr) :: deepatmo_divzu_mc
    type(c_ptr) :: deepatmo_gradh_ifc
    type(c_ptr) :: deepatmo_gradh_mc
    type(c_ptr) :: deepatmo_invr_ifc
    type(c_ptr) :: deepatmo_invr_mc
    type(c_ptr) :: exner_exfac
    type(c_ptr) :: exner_ref_mc
    type(c_ptr) :: hmask_dd3d
    type(c_ptr) :: inv_ddqz_z_full
    type(c_ptr) :: pg_edgeblk
    type(c_ptr) :: pg_edgeidx
    type(c_ptr) :: pg_exdist
    integer(kind=c_int) :: pg_listdim
    type(c_ptr) :: pg_vertidx
    type(c_ptr) :: rayleigh_vn
    type(c_ptr) :: rayleigh_w
    type(c_ptr) :: rho_ref_mc
    type(c_ptr) :: rho_ref_me
    type(c_ptr) :: scalfac_dd3d
    type(c_ptr) :: theta_ref_ic
    type(c_ptr) :: theta_ref_mc
    type(c_ptr) :: theta_ref_me
    type(c_ptr) :: vertidx_gradp
    type(c_ptr) :: vwind_expl_wgt
    type(c_ptr) :: vwind_impl_wgt
    type(c_ptr) :: wgtfac_c
    type(c_ptr) :: wgtfac_e
    type(c_ptr) :: wgtfacq1_c
    type(c_ptr) :: wgtfacq_c
    type(c_ptr) :: wgtfacq_e
    type(c_ptr) :: zdiff_gradp
  end type dace_t_nh_metrics

  type, bind(c) :: dace_t_prepare_adv
    integer(kind=c_int) :: f2dace_SA_mass_flx_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_mass_flx_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_mass_flx_ic_d_2_s
    integer(kind=c_int) :: f2dace_SA_mass_flx_me_d_0_s
    integer(kind=c_int) :: f2dace_SA_mass_flx_me_d_1_s
    integer(kind=c_int) :: f2dace_SA_mass_flx_me_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_traj_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_traj_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_traj_d_2_s
    integer(kind=c_int) :: f2dace_SA_vol_flx_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_vol_flx_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_vol_flx_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_me_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_me_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mass_flx_me_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_traj_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_traj_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_traj_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vol_flx_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vol_flx_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vol_flx_ic_d_2_s
    type(c_ptr) :: mass_flx_ic
    type(c_ptr) :: mass_flx_me
    type(c_ptr) :: vn_traj
    type(c_ptr) :: vol_flx_ic
  end type dace_t_prepare_adv

  type, bind(c) :: dace_t_nh_ref
    integer(kind=c_int) :: f2dace_SA_vn_ref_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_ref_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_ref_d_2_s
    integer(kind=c_int) :: f2dace_SA_w_ref_d_0_s
    integer(kind=c_int) :: f2dace_SA_w_ref_d_1_s
    integer(kind=c_int) :: f2dace_SA_w_ref_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_ref_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_ref_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_ref_d_2_s
    integer(kind=c_int) :: f2dace_SOA_w_ref_d_0_s
    integer(kind=c_int) :: f2dace_SOA_w_ref_d_1_s
    integer(kind=c_int) :: f2dace_SOA_w_ref_d_2_s
    type(c_ptr) :: vn_ref
    type(c_ptr) :: w_ref
  end type dace_t_nh_ref

  type, bind(c) :: dace_t_nh_prog
    integer(kind=c_int) :: f2dace_SA_exner_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_v_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_v_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_v_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_d_2_s
    integer(kind=c_int) :: f2dace_SA_w_d_0_s
    integer(kind=c_int) :: f2dace_SA_w_d_1_s
    integer(kind=c_int) :: f2dace_SA_w_d_2_s
    integer(kind=c_int) :: f2dace_SOA_exner_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_d_2_s
    integer(kind=c_int) :: f2dace_SOA_w_d_0_s
    integer(kind=c_int) :: f2dace_SOA_w_d_1_s
    integer(kind=c_int) :: f2dace_SOA_w_d_2_s
    type(c_ptr) :: exner
    type(c_ptr) :: rho
    type(c_ptr) :: theta_v
    type(c_ptr) :: vn
    type(c_ptr) :: w
  end type dace_t_nh_prog

  type, bind(c) :: dace_t_nh_diag
    integer(kind=c_int) :: f2dace_SA_ddt_exner_phy_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_exner_phy_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_exner_phy_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_adv_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_adv_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_adv_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_apc_pc_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_apc_pc_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_apc_pc_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_apc_pc_d_3_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_pc_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_pc_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_pc_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_cor_pc_d_3_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dmp_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dmp_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dmp_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dyn_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dyn_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_dyn_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_grf_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_grf_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_grf_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_iau_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_iau_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_iau_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_pgr_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_pgr_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_pgr_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phd_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phd_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phd_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phy_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phy_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_phy_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_ray_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_ray_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_vn_ray_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_w_adv_pc_d_0_s
    integer(kind=c_int) :: f2dace_SA_ddt_w_adv_pc_d_1_s
    integer(kind=c_int) :: f2dace_SA_ddt_w_adv_pc_d_2_s
    integer(kind=c_int) :: f2dace_SA_ddt_w_adv_pc_d_3_s
    integer(kind=c_int) :: f2dace_SA_exner_dyn_incr_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_dyn_incr_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_dyn_incr_d_2_s
    integer(kind=c_int) :: f2dace_SA_exner_incr_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_incr_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_incr_d_2_s
    integer(kind=c_int) :: f2dace_SA_exner_pr_d_0_s
    integer(kind=c_int) :: f2dace_SA_exner_pr_d_1_s
    integer(kind=c_int) :: f2dace_SA_exner_pr_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_bdy_mflx_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_bdy_mflx_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_bdy_mflx_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_mflx_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_mflx_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_mflx_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_rho_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_rho_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_rho_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_thv_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_thv_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_thv_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_vn_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_vn_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_vn_d_2_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_w_d_0_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_w_d_1_s
    integer(kind=c_int) :: f2dace_SA_grf_tend_w_d_2_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_sv_d_0_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_sv_d_1_s
    integer(kind=c_int) :: f2dace_SA_mass_fl_e_sv_d_2_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SA_mflx_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SA_rho_incr_d_0_s
    integer(kind=c_int) :: f2dace_SA_rho_incr_d_1_s
    integer(kind=c_int) :: f2dace_SA_rho_incr_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SA_theta_v_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_int_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_int_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_int_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_ie_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SA_vn_incr_d_0_s
    integer(kind=c_int) :: f2dace_SA_vn_incr_d_1_s
    integer(kind=c_int) :: f2dace_SA_vn_incr_d_2_s
    integer(kind=c_int) :: f2dace_SA_vt_d_0_s
    integer(kind=c_int) :: f2dace_SA_vt_d_1_s
    integer(kind=c_int) :: f2dace_SA_vt_d_2_s
    integer(kind=c_int) :: f2dace_SA_w_concorr_c_d_0_s
    integer(kind=c_int) :: f2dace_SA_w_concorr_c_d_1_s
    integer(kind=c_int) :: f2dace_SA_w_concorr_c_d_2_s
    integer(kind=c_int) :: f2dace_SA_w_int_d_0_s
    integer(kind=c_int) :: f2dace_SA_w_int_d_1_s
    integer(kind=c_int) :: f2dace_SA_w_int_d_2_s
    integer(kind=c_int) :: f2dace_SA_w_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SA_w_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SA_w_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_exner_phy_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_exner_phy_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_exner_phy_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_adv_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_adv_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_adv_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_apc_pc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_apc_pc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_apc_pc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_apc_pc_d_3_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_pc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_pc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_pc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_cor_pc_d_3_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dmp_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dmp_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dmp_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dyn_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dyn_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_dyn_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_grf_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_grf_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_grf_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_iau_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_iau_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_iau_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_pgr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_pgr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_pgr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phd_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phd_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phd_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phy_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phy_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_phy_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_ray_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_ray_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_vn_ray_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_w_adv_pc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_ddt_w_adv_pc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_ddt_w_adv_pc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_ddt_w_adv_pc_d_3_s
    integer(kind=c_int) :: f2dace_SOA_exner_dyn_incr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_dyn_incr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_dyn_incr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_exner_incr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_incr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_incr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_exner_pr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_exner_pr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_exner_pr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_bdy_mflx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_bdy_mflx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_bdy_mflx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_mflx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_mflx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_mflx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_rho_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_rho_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_rho_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_thv_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_thv_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_thv_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_vn_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_vn_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_vn_d_2_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_w_d_0_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_w_d_1_s
    integer(kind=c_int) :: f2dace_SOA_grf_tend_w_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_sv_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_sv_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mass_fl_e_sv_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_mflx_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_rho_incr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rho_incr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rho_incr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_int_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_int_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_int_d_2_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_theta_v_ic_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_int_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_int_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_int_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_ie_ubc_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vn_incr_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vn_incr_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vn_incr_d_2_s
    integer(kind=c_int) :: f2dace_SOA_vt_d_0_s
    integer(kind=c_int) :: f2dace_SOA_vt_d_1_s
    integer(kind=c_int) :: f2dace_SOA_vt_d_2_s
    integer(kind=c_int) :: f2dace_SOA_w_concorr_c_d_0_s
    integer(kind=c_int) :: f2dace_SOA_w_concorr_c_d_1_s
    integer(kind=c_int) :: f2dace_SOA_w_concorr_c_d_2_s
    integer(kind=c_int) :: f2dace_SOA_w_int_d_0_s
    integer(kind=c_int) :: f2dace_SOA_w_int_d_1_s
    integer(kind=c_int) :: f2dace_SOA_w_int_d_2_s
    integer(kind=c_int) :: f2dace_SOA_w_ubc_d_0_s
    integer(kind=c_int) :: f2dace_SOA_w_ubc_d_1_s
    integer(kind=c_int) :: f2dace_SOA_w_ubc_d_2_s
    type(c_ptr) :: ddt_exner_phy
    type(c_ptr) :: ddt_vn_adv
    integer(kind=c_int) :: ddt_vn_adv_is_associated
    type(c_ptr) :: ddt_vn_apc_pc
    type(c_ptr) :: ddt_vn_cor
    integer(kind=c_int) :: ddt_vn_cor_is_associated
    type(c_ptr) :: ddt_vn_cor_pc
    type(c_ptr) :: ddt_vn_dmp
    integer(kind=c_int) :: ddt_vn_dmp_is_associated
    type(c_ptr) :: ddt_vn_dyn
    integer(kind=c_int) :: ddt_vn_dyn_is_associated
    type(c_ptr) :: ddt_vn_grf
    integer(kind=c_int) :: ddt_vn_grf_is_associated
    type(c_ptr) :: ddt_vn_iau
    integer(kind=c_int) :: ddt_vn_iau_is_associated
    type(c_ptr) :: ddt_vn_pgr
    integer(kind=c_int) :: ddt_vn_pgr_is_associated
    type(c_ptr) :: ddt_vn_phd
    integer(kind=c_int) :: ddt_vn_phd_is_associated
    type(c_ptr) :: ddt_vn_phy
    type(c_ptr) :: ddt_vn_ray
    integer(kind=c_int) :: ddt_vn_ray_is_associated
    type(c_ptr) :: ddt_w_adv_pc
    type(c_ptr) :: exner_dyn_incr
    type(c_ptr) :: exner_incr
    type(c_ptr) :: exner_pr
    type(c_ptr) :: grf_bdy_mflx
    type(c_ptr) :: grf_tend_mflx
    type(c_ptr) :: grf_tend_rho
    type(c_ptr) :: grf_tend_thv
    type(c_ptr) :: grf_tend_vn
    type(c_ptr) :: grf_tend_w
    type(c_ptr) :: mass_fl_e
    type(c_ptr) :: mass_fl_e_sv
    real(kind=c_double) :: max_vcfl_dyn
    type(c_ptr) :: mflx_ic_int
    type(c_ptr) :: mflx_ic_ubc
    type(c_ptr) :: rho_ic
    type(c_ptr) :: rho_ic_int
    type(c_ptr) :: rho_ic_ubc
    type(c_ptr) :: rho_incr
    type(c_ptr) :: theta_v_ic
    type(c_ptr) :: theta_v_ic_int
    type(c_ptr) :: theta_v_ic_ubc
    type(c_ptr) :: vn_ie
    type(c_ptr) :: vn_ie_int
    type(c_ptr) :: vn_ie_ubc
    type(c_ptr) :: vn_incr
    type(c_ptr) :: vt
    type(c_ptr) :: w_concorr_c
    type(c_ptr) :: w_int
    type(c_ptr) :: w_ubc
  end type dace_t_nh_diag

  type, bind(c) :: dace_t_nh_state
    ! C++: int __f2dace_SA_prog_d_0_s = {}; (missing)
    integer(kind=c_int) :: f2dace_SA_prog_d_0_s
    ! C++: int __f2dace_SOA_prog_d_0_s = {}; (missing)
    integer(kind=c_int) :: f2dace_SOA_prog_d_0_s
    ! C++: t_nh_diag *diag = {};
    type(c_ptr) :: diag
    ! C++: t_nh_metrics *metrics = {};
    type(c_ptr) :: metrics
    ! C++: t_nh_prog **prog = {}; (missing)
    type(c_ptr) :: prog
    ! C++: t_nh_ref *ref = {};
    type(c_ptr) :: ref
  end type dace_t_nh_state

  type, bind(c) :: dace_t_grid_domain_decomp_info
    integer(kind=c_int) :: f2dace_SA_owner_mask_d_0_s
    integer(kind=c_int) :: f2dace_SA_owner_mask_d_1_s
    integer(kind=c_int) :: f2dace_SOA_owner_mask_d_0_s
    integer(kind=c_int) :: f2dace_SOA_owner_mask_d_1_s
    type(c_ptr) :: owner_mask
  end type dace_t_grid_domain_decomp_info

  type, bind(c) :: dace_t_grid_cells
    integer(kind=c_int) :: f2dace_SA_area_d_0_s
    integer(kind=c_int) :: f2dace_SA_area_d_1_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_end_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_end_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SA_neighbor_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_neighbor_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_neighbor_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_neighbor_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_neighbor_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_neighbor_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_start_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_start_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_start_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_area_d_0_s
    integer(kind=c_int) :: f2dace_SOA_area_d_1_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_end_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_end_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_neighbor_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_start_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_start_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_start_index_d_0_s
    type(c_ptr) :: area
    type(c_ptr) :: decomp_info
    type(c_ptr) :: edge_blk
    type(c_ptr) :: edge_idx
    type(c_ptr) :: end_blk
    type(c_ptr) :: end_block
    type(c_ptr) :: end_index
    type(c_ptr) :: neighbor_blk
    type(c_ptr) :: neighbor_idx
    type(c_ptr) :: start_blk
    type(c_ptr) :: start_block
    type(c_ptr) :: start_index
  end type dace_t_grid_cells

  type, bind(c) :: dace_t_int_state
    integer(kind=c_int) :: f2dace_SA_c_lin_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_c_lin_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_c_lin_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_cells_aw_verts_d_0_s
    integer(kind=c_int) :: f2dace_SA_cells_aw_verts_d_1_s
    integer(kind=c_int) :: f2dace_SA_cells_aw_verts_d_2_s
    integer(kind=c_int) :: f2dace_SA_e_bln_c_s_d_0_s
    integer(kind=c_int) :: f2dace_SA_e_bln_c_s_d_1_s
    integer(kind=c_int) :: f2dace_SA_e_bln_c_s_d_2_s
    integer(kind=c_int) :: f2dace_SA_e_flx_avg_d_0_s
    integer(kind=c_int) :: f2dace_SA_e_flx_avg_d_1_s
    integer(kind=c_int) :: f2dace_SA_e_flx_avg_d_2_s
    integer(kind=c_int) :: f2dace_SA_geofac_div_d_0_s
    integer(kind=c_int) :: f2dace_SA_geofac_div_d_1_s
    integer(kind=c_int) :: f2dace_SA_geofac_div_d_2_s
    integer(kind=c_int) :: f2dace_SA_geofac_grdiv_d_0_s
    integer(kind=c_int) :: f2dace_SA_geofac_grdiv_d_1_s
    integer(kind=c_int) :: f2dace_SA_geofac_grdiv_d_2_s
    integer(kind=c_int) :: f2dace_SA_geofac_grg_d_0_s
    integer(kind=c_int) :: f2dace_SA_geofac_grg_d_1_s
    integer(kind=c_int) :: f2dace_SA_geofac_grg_d_2_s
    integer(kind=c_int) :: f2dace_SA_geofac_grg_d_3_s
    integer(kind=c_int) :: f2dace_SA_geofac_n2s_d_0_s
    integer(kind=c_int) :: f2dace_SA_geofac_n2s_d_1_s
    integer(kind=c_int) :: f2dace_SA_geofac_n2s_d_2_s
    integer(kind=c_int) :: f2dace_SA_geofac_rot_d_0_s
    integer(kind=c_int) :: f2dace_SA_geofac_rot_d_1_s
    integer(kind=c_int) :: f2dace_SA_geofac_rot_d_2_s
    integer(kind=c_int) :: f2dace_SA_nudgecoeff_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_nudgecoeff_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_pos_on_tplane_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_pos_on_tplane_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_pos_on_tplane_e_d_2_s
    integer(kind=c_int) :: f2dace_SA_pos_on_tplane_e_d_3_s
    integer(kind=c_int) :: f2dace_SA_rbf_vec_coeff_e_d_0_s
    integer(kind=c_int) :: f2dace_SA_rbf_vec_coeff_e_d_1_s
    integer(kind=c_int) :: f2dace_SA_rbf_vec_coeff_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_c_lin_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_c_lin_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_c_lin_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_cells_aw_verts_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cells_aw_verts_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cells_aw_verts_d_2_s
    integer(kind=c_int) :: f2dace_SOA_e_bln_c_s_d_0_s
    integer(kind=c_int) :: f2dace_SOA_e_bln_c_s_d_1_s
    integer(kind=c_int) :: f2dace_SOA_e_bln_c_s_d_2_s
    integer(kind=c_int) :: f2dace_SOA_e_flx_avg_d_0_s
    integer(kind=c_int) :: f2dace_SOA_e_flx_avg_d_1_s
    integer(kind=c_int) :: f2dace_SOA_e_flx_avg_d_2_s
    integer(kind=c_int) :: f2dace_SOA_geofac_div_d_0_s
    integer(kind=c_int) :: f2dace_SOA_geofac_div_d_1_s
    integer(kind=c_int) :: f2dace_SOA_geofac_div_d_2_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grdiv_d_0_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grdiv_d_1_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grdiv_d_2_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grg_d_0_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grg_d_1_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grg_d_2_s
    integer(kind=c_int) :: f2dace_SOA_geofac_grg_d_3_s
    integer(kind=c_int) :: f2dace_SOA_geofac_n2s_d_0_s
    integer(kind=c_int) :: f2dace_SOA_geofac_n2s_d_1_s
    integer(kind=c_int) :: f2dace_SOA_geofac_n2s_d_2_s
    integer(kind=c_int) :: f2dace_SOA_geofac_rot_d_0_s
    integer(kind=c_int) :: f2dace_SOA_geofac_rot_d_1_s
    integer(kind=c_int) :: f2dace_SOA_geofac_rot_d_2_s
    integer(kind=c_int) :: f2dace_SOA_nudgecoeff_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_nudgecoeff_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_pos_on_tplane_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_pos_on_tplane_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_pos_on_tplane_e_d_2_s
    integer(kind=c_int) :: f2dace_SOA_pos_on_tplane_e_d_3_s
    integer(kind=c_int) :: f2dace_SOA_rbf_vec_coeff_e_d_0_s
    integer(kind=c_int) :: f2dace_SOA_rbf_vec_coeff_e_d_1_s
    integer(kind=c_int) :: f2dace_SOA_rbf_vec_coeff_e_d_2_s
    type(c_ptr) :: c_lin_e
    type(c_ptr) :: cells_aw_verts
    type(c_ptr) :: e_bln_c_s
    type(c_ptr) :: e_flx_avg
    type(c_ptr) :: geofac_div
    type(c_ptr) :: geofac_grdiv
    type(c_ptr) :: geofac_grg
    type(c_ptr) :: geofac_n2s
    type(c_ptr) :: geofac_rot
    type(c_ptr) :: nudgecoeff_e
    type(c_ptr) :: pos_on_tplane_e
    type(c_ptr) :: rbf_vec_coeff_e
  end type dace_t_int_state

  type, bind(c) :: dace_t_grid_vertices
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_cell_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_cell_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_0_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_1_s
    integer(kind=c_int) :: f2dace_SA_edge_blk_d_2_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_0_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_1_s
    integer(kind=c_int) :: f2dace_SA_edge_idx_d_2_s
    integer(kind=c_int) :: f2dace_SA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SA_start_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cell_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_cell_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_0_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_1_s
    integer(kind=c_int) :: f2dace_SOA_edge_blk_d_2_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_0_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_1_s
    integer(kind=c_int) :: f2dace_SOA_edge_idx_d_2_s
    integer(kind=c_int) :: f2dace_SOA_end_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_end_index_d_0_s
    integer(kind=c_int) :: f2dace_SOA_start_block_d_0_s
    integer(kind=c_int) :: f2dace_SOA_start_index_d_0_s
    type(c_ptr) :: cell_blk
    type(c_ptr) :: cell_idx
    type(c_ptr) :: edge_blk
    type(c_ptr) :: edge_idx
    type(c_ptr) :: end_block
    type(c_ptr) :: end_index
    type(c_ptr) :: start_block
    type(c_ptr) :: start_index
  end type dace_t_grid_vertices

  type, bind(c) :: dace_t_patch
    type(c_ptr) :: cells
    type(c_ptr) :: edges
    integer(kind=c_int) :: id
    integer(kind=c_int) :: n_childdom
    integer(kind=c_int) :: nblks_c
    integer(kind=c_int) :: nblks_e
    integer(kind=c_int) :: nblks_v
    integer(kind=c_int) :: nlev
    integer(kind=c_int) :: nlevp1
    integer(kind=c_int) :: nshift
    type(c_ptr) :: verts
  end type dace_t_patch

end module mo_solve_nh_dace_structs