#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================

from buildbot_config import BuildbotConfig
from util import WhitespaceSeperatedList, WhitespaceSeperatedFiles, WhitespaceSeperatedDict
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click
import sys

@click.command()
@click.argument("experiment_names", type=WhitespaceSeperatedFiles())
@click.option("--builders", type=WhitespaceSeperatedList(), help="names of the builders to add")
@click.option("--with-configureflags", type=WhitespaceSeperatedDict(), help="only use builders with these configure options")
@click.option("--without-configureflags", type=WhitespaceSeperatedDict(), help="discard bulders with these configure options")
@click.option("--machines", type=WhitespaceSeperatedList(), help="the machine name to add the builder")
@click.option("--runflags", type=WhitespaceSeperatedDict(), help="arguments to be added to the runscript generator")
@click.option("--list", "list_name", type=str, help="the buildbot configuration list", required=True)
def addexp(experiment_names, builders, with_configureflags, without_configureflags, machines, runflags, list_name):

    full_list_name = buildbot_list_path / list_name

    if Path(full_list_name).exists():
      thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
      print("did not find experiment list {}".format(full_list_name))
      sys.exit(1)

    thisList.add_experiments(experiment_names, builders=builders, machines=machines, with_config=with_configureflags, without_config=without_configureflags, run_flags=runflags)

    thisList.to_pickle(full_list_name)

if __name__ == "__main__":
    addexp()


